import os

from dotenv import load_dotenv

load_dotenv()


class GeminiDocumentGenerator:
    """
    Generates legal document drafts using Gemini.
    Demo mode is available for testing without an API key.
    """

    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "").strip()
        self.model_name = os.getenv(
            "GEMINI_MODEL",
            "gemini-2.5-flash"
        )
        self.demo_mode = (
            os.getenv("DEMO_MODE", "true").lower() == "true"
        )

        self.model = None

        if not self.demo_mode:
            self._configure_gemini()

    def _configure_gemini(self):
        """
        Configure Gemini when real AI mode is enabled.
        """

        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY is missing. "
                "Add your Gemini API key to the .env file."
            )

        try:
            import google.generativeai as genai

            genai.configure(api_key=self.api_key)

            self.model = genai.GenerativeModel(
                self.model_name
            )

        except ImportError as error:
            raise RuntimeError(
                "google-generativeai package is not installed."
            ) from error

    def generate_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: str,
    ) -> str:
        """
        Generate a legal document draft.
        """

        if self.demo_mode:
            return self._generate_demo_document(
                document_type=document_type,
                parties=parties,
                terms=terms,
                effective_date=effective_date,
            )

        return self._generate_with_gemini(
            document_type=document_type,
            parties=parties,
            terms=terms,
            effective_date=effective_date,
        )

    def _generate_with_gemini(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: str,
    ) -> str:
        """
        Generate the document using Gemini.
        """

        prompt = f"""
You are an AI legal document drafting assistant.

Create a clear and professional draft of the following
legal document.

Document Type:
{document_type}

Parties:
{parties}

Effective Date:
{effective_date}

Terms and Conditions:
{terms}

Requirements:

1. Use a professional legal-document structure.
2. Include a clear title.
3. Include the parties section.
4. Include the effective date.
5. Convert the provided terms into organized clauses.
6. Include appropriate numbered sections.
7. Do not invent important facts that were not provided.
8. Clearly treat the result as an AI-generated draft.
9. Add a final note recommending review by a qualified
   legal professional.

Return only the document text.
"""

        try:
            response = self.model.generate_content(prompt)

            content = getattr(
                response,
                "text",
                None,
            )

            if not content:
                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            return content.strip()

        except Exception as error:
            raise RuntimeError(
                f"Gemini document generation failed: {error}"
            ) from error

    def _generate_demo_document(
        self,
        document_type: str,
        parties: str,
        terms: str,
        effective_date: str,
    ) -> str:
        """
        Generate a sample document without using Gemini.
        """

        term_list = [
            term.strip()
            for term in terms.split(";")
            if term.strip()
        ]

        clauses = []

        for index, term in enumerate(
            term_list,
            start=1,
        ):
            clauses.append(
                f"{index}. {term}"
            )

        if not clauses:
            clauses.append(
                "1. The parties agree to the terms "
                "and conditions specified in this document."
            )

        clauses_text = "\n\n".join(clauses)

        return f"""LEGAL DOCUMENT

{document_type.upper()}

1. PARTIES

{parties}

2. EFFECTIVE DATE

This document shall be effective from {effective_date}.

3. TERMS AND CONDITIONS

{clauses_text}

4. GENERAL PROVISIONS

The parties agree to comply with the terms and
conditions stated in this document.

5. REVIEW NOTICE

This document is an AI-assisted draft generated by
LegalEase. It should be reviewed by a qualified legal
professional before signing or use.

---
LegalEase
AI-Powered Legal Document Generator
"""